spring:
  application:
    name: microservices
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: eureka


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



